package com.freshair.freshairproject;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class AuditFinding implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	private java.lang.String processName;
	private java.lang.String description;

	public AuditFinding() {
	}

	public java.lang.String getProcessName() {
		return this.processName;
	}

	public void setProcessName(java.lang.String processName) {
		this.processName = processName;
	}

	public java.lang.String getDescription() {
		return this.description;
	}

	public void setDescription(java.lang.String description) {
		this.description = description;
	}

	public AuditFinding(java.lang.String processName,
			java.lang.String description) {
		this.processName = processName;
		this.description = description;
	}

}