package com.freshair.freshairproject;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class AuditFinding implements java.io.Serializable {

    static final long serialVersionUID = 1L;

    public AuditFinding() {
    }




}