package com.freshair.freshairproject;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class AuditFindings implements java.io.Serializable {

    static final long serialVersionUID = 1L;

    public AuditFindings() {
    }




}