package com.freshair.freshairproject;

/**
 * This class was automatically generated by the data modeler tool.
 */

@javax.xml.bind.annotation.XmlRootElement
public class DacMetrics implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	private java.lang.Integer cpuUsage;
	private java.lang.Integer temperature;
	private java.lang.Integer backupBatteryLife;

	public DacMetrics() {
	}

	public java.lang.Integer getCpuUsage() {
		return this.cpuUsage;
	}

	public void setCpuUsage(java.lang.Integer cpuUsage) {
		this.cpuUsage = cpuUsage;
	}

	public java.lang.Integer getTemperature() {
		return this.temperature;
	}

	public void setTemperature(java.lang.Integer temperature) {
		this.temperature = temperature;
	}

	public java.lang.Integer getBackupBatteryLife() {
		return this.backupBatteryLife;
	}

	public void setBackupBatteryLife(java.lang.Integer backupBatteryLife) {
		this.backupBatteryLife = backupBatteryLife;
	}

	public DacMetrics(java.lang.Integer cpuUsage,
			java.lang.Integer temperature, java.lang.Integer backupBatteryLife) {
		this.cpuUsage = cpuUsage;
		this.temperature = temperature;
		this.backupBatteryLife = backupBatteryLife;
	}

}