package com.freshair.freshairproject;

/**
 * This class was automatically generated by the data modeler tool.
 */

@javax.xml.bind.annotation.XmlRootElement
public class DacSolution implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	private java.lang.String id;
	private java.lang.String metricsUrl;

	private java.lang.String customerName;

	private java.lang.String customerEmail;

	public DacSolution() {
	}

	public java.lang.String getId() {
		return this.id;
	}

	public void setId(java.lang.String id) {
		this.id = id;
	}

	public java.lang.String getMetricsUrl() {
		return this.metricsUrl;
	}

	public void setMetricsUrl(java.lang.String metricsUrl) {
		this.metricsUrl = metricsUrl;
	}

	public java.lang.String getCustomerName() {
		return this.customerName;
	}

	public void setCustomerName(java.lang.String customerName) {
		this.customerName = customerName;
	}

	public java.lang.String getCustomerEmail() {
		return this.customerEmail;
	}

	public void setCustomerEmail(java.lang.String customerEmail) {
		this.customerEmail = customerEmail;
	}

	public DacSolution(java.lang.String id, java.lang.String metricsUrl,
			java.lang.String customerName, java.lang.String customerEmail) {
		this.id = id;
		this.metricsUrl = metricsUrl;
		this.customerName = customerName;
		this.customerEmail = customerEmail;
	}

}