package com.freshair.freshairproject;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class FinanceData implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	private java.util.List<com.freshair.freshairproject.Sale> sales;

	public FinanceData() {
	}

	public java.util.List<com.freshair.freshairproject.Sale> getSales() {
		return this.sales;
	}

	public void setSales(java.util.List<com.freshair.freshairproject.Sale> sales) {
		this.sales = sales;
	}

	public FinanceData(java.util.List<com.freshair.freshairproject.Sale> sales) {
		this.sales = sales;
	}

}