package com.freshair.freshairproject;

/**
 * This class was automatically generated by the data modeler tool.
 */

@javax.xml.bind.annotation.XmlRootElement
public class Sale implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	private java.lang.String date;
	private java.lang.Integer amount;

	public Sale() {
	}

	public java.lang.String getDate() {
		return this.date;
	}

	public void setDate(java.lang.String date) {
		this.date = date;
	}

	public java.lang.Integer getAmount() {
		return this.amount;
	}

	public void setAmount(java.lang.Integer amount) {
		this.amount = amount;
	}

	public Sale(java.lang.String date, java.lang.Integer amount) {
		this.date = date;
		this.amount = amount;
	}

}