package com.freshair.freshairproject;

/**
 * This class was automatically generated by the data modeler tool.
 */

@javax.xml.bind.annotation.XmlRootElement
public class TestObject implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	private java.lang.String name;

	public TestObject() {
	}

	public java.lang.String getName() {
		return this.name;
	}

	public void setName(java.lang.String name) {
		this.name = name;
	}

	public TestObject(java.lang.String name) {
		this.name = name;
	}

}