package com.freshair.freshairproject;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class WarehouseStatus implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	private java.util.List<java.lang.String> items;

	public WarehouseStatus() {
	}

	public java.util.List<java.lang.String> getItems() {
		return this.items;
	}

	public void setItems(java.util.List<java.lang.String> items) {
		this.items = items;
	}

	public WarehouseStatus(java.util.List<java.lang.String> items) {
		this.items = items;
	}

}