package com.freshair.freshairproject;

/**
 * This class was automatically generated by the data modeler tool.
 */

@javax.xml.bind.annotation.XmlRootElement
public class WarehouseStatus implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	private java.util.List<com.freshair.freshairproject.Item> items;

	public WarehouseStatus() {
	}

	public java.util.List<com.freshair.freshairproject.Item> getItems() {
		return this.items;
	}

	public void setItems(java.util.List<com.freshair.freshairproject.Item> items) {
		this.items = items;
	}

	public WarehouseStatus(
			java.util.List<com.freshair.freshairproject.Item> items) {
		this.items = items;
	}

}